// Samples each card's own border colour so the frame behind it can match.
// Run from the repo root after importing card art:  node scripts/sample-borders.mjs
import sharp from 'sharp'
import { readdirSync, writeFileSync } from 'node:fs'

const DIR = 'public/cards'
const OUT = 'app/(app)/vending/cardBorders.ts'

const median = (xs) => xs.sort((a, b) => a - b)[xs.length >> 1]

const entries = []
for (const f of readdirSync(DIR).filter((x) => x.endsWith('.webp'))) {
  const { data, info } = await sharp(`${DIR}/${f}`)
    .removeAlpha().raw().toBuffer({ resolveWithObject: true })
  const { width: W, height: H, channels: C } = info
  const at = (x, y) => {
    const i = (y * W + x) * C
    return [data[i], data[i + 1], data[i + 2]]
  }

  // A ring just inside the cut, skipping the corners - those round off and
  // pick up whatever sits behind the card.
  const px = []
  const inset = Math.round(W * 0.012)
  const skip = Math.round(W * 0.1)
  for (let x = skip; x < W - skip; x += 3) { px.push(at(x, inset)); px.push(at(x, H - 1 - inset)) }
  for (let y = skip; y < H - skip; y += 3) { px.push(at(inset, y)); px.push(at(W - 1 - inset, y)) }

  // Quantised: per-card medians differ by a digit or two purely from encoder
  // noise, which would make almost every card its own entry for a colour
  // nobody could tell apart. Rounding collapses that and keeps the real
  // differences, like the duller yellow on the holo scans.
  const rgb = [0, 1, 2].map((ch) => Math.round(median(px.map((p) => p[ch])) / 8) * 8)
    .map((v) => Math.min(255, v))
  const hex = '#' + rgb.map((v) => v.toString(16).padStart(2, '0')).join('')
  entries.push([`/cards/${f}`, hex])
}

entries.sort((a, b) => a[0].localeCompare(b[0]))

// Most cards land on the same few yellows, so the common one becomes the
// fallback and only the outliers need listing.
const freq = new Map()
for (const [, hex] of entries) freq.set(hex, (freq.get(hex) ?? 0) + 1)
const fallback = [...freq.entries()].sort((a, b) => b[1] - a[1])[0][0]
const outliers = entries.filter(([, hex]) => hex !== fallback)

writeFileSync(OUT,
`// Generated by scripts/sample-borders.mjs - do not edit by hand.
//
// Each card's own border colour, read off the scan. ConditionedCard paints
// the frame behind the art with this so the card's border and the frame it
// sits in are the same yellow, and widening one side reads as a bad cut
// rather than a coloured mat.

/** The yellow ${freq.get(fallback)} of ${entries.length} cards share. */
export const DEFAULT_BORDER = '${fallback}'

/** Only cards whose scan differs from the common yellow. */
export const CARD_BORDER: Record<string, string> = {
${outliers.map(([k, v]) => `  '${k}': '${v}',`).join('\n')}
}

export function borderColor(imageUrl: string): string {
  return CARD_BORDER[imageUrl] ?? DEFAULT_BORDER
}
`)

console.log(`cards     ${entries.length}`)
console.log(`fallback  ${fallback} (${freq.get(fallback)} cards)`)
console.log(`outliers  ${outliers.length}`)
console.log(`distinct  ${freq.size}`)
