-- Raffle tickets: admin-defined collectibles rolled at random into the vending
-- machine alongside packs, bought with tokens.
--
-- Already applied to the live database. Kept here as the record of the change.
--
-- Shape:
--   raffle_tickets        ticket definitions (price, rarity, window, allotment)
--   vending_ticket_stock  which tickets sit in the machine for a given cycle
--   user_raffle_tickets   what each member holds
--
-- Rarity is the appearance weight, not just a label - see raffle_rarity_chance.
-- Ticket art is admin-uploaded at runtime, so unlike packs/cards (static files
-- under /public) it lives in the public "raffle-tickets" Storage bucket.

create table if not exists public.raffle_tickets (
  id                bigint generated by default as identity primary key,
  name              text not null,
  description       text,
  token_price       integer not null default 1 check (token_price >= 0),
  rarity            text not null default 'common'
                    check (rarity in ('common','uncommon','rare','ultra','legendary')),
  image_url         text,
  starts_at         timestamptz,
  ends_at           timestamptz,
  total_quantity    integer not null check (total_quantity > 0),
  claimed_quantity  integer not null default 0 check (claimed_quantity >= 0),
  is_active         boolean not null default true,
  created_at        timestamptz not null default now(),
  created_by        uuid references public.profiles(id) on delete set null,
  constraint raffle_tickets_not_oversold check (claimed_quantity <= total_quantity),
  constraint raffle_tickets_window check (ends_at is null or starts_at is null or ends_at > starts_at)
);

create table if not exists public.vending_ticket_stock (
  id         bigint generated by default as identity primary key,
  cycle_no   bigint not null,
  ticket_id  bigint not null references public.raffle_tickets(id) on delete cascade,
  quantity   integer not null default 0 check (quantity >= 0),
  unique (cycle_no, ticket_id)
);

create table if not exists public.user_raffle_tickets (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references public.profiles(id) on delete cascade,
  ticket_id   bigint not null references public.raffle_tickets(id) on delete cascade,
  cycle_no    bigint,
  acquired_at timestamptz not null default now()
);

create index if not exists user_raffle_tickets_user_idx on public.user_raffle_tickets (user_id);
create index if not exists vending_ticket_stock_cycle_idx on public.vending_ticket_stock (cycle_no);

alter table public.raffle_tickets       enable row level security;
alter table public.vending_ticket_stock enable row level security;
alter table public.user_raffle_tickets  enable row level security;

create policy raffle_tickets_select on public.raffle_tickets
  for select using (public.is_member());
create policy raffle_tickets_write on public.raffle_tickets
  for all using (public.is_admin()) with check (public.is_admin());
create policy vending_ticket_stock_select on public.vending_ticket_stock
  for select using (public.is_member());
create policy user_raffle_tickets_select on public.user_raffle_tickets
  for select using (user_id = auth.uid() or public.is_mod());

-- Storage bucket for admin-uploaded ticket art (public read, admin write).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('raffle-tickets', 'raffle-tickets', true, 2097152,
        array['image/png','image/jpeg','image/webp','image/gif'])
on conflict (id) do nothing;

create policy "raffle ticket art is publicly readable" on storage.objects
  for select using (bucket_id = 'raffle-tickets');
create policy "admins upload raffle ticket art" on storage.objects
  for insert to authenticated with check (bucket_id = 'raffle-tickets' and public.is_admin());
create policy "admins update raffle ticket art" on storage.objects
  for update to authenticated using (bucket_id = 'raffle-tickets' and public.is_admin());
create policy "admins delete raffle ticket art" on storage.objects
  for delete to authenticated using (bucket_id = 'raffle-tickets' and public.is_admin());

-- Per-cycle chance a ticket of each rarity is rolled into the machine.
create or replace function public.raffle_rarity_chance(p_rarity text)
returns numeric language sql immutable as $function$
  select case p_rarity
    when 'common' then 0.50 when 'uncommon' then 0.30 when 'rare' then 0.15
    when 'ultra'  then 0.06 when 'legendary' then 0.02 else 0.0 end;
$function$;

-- build_vending_stock gains ticket rolling (pack logic unchanged), and
-- vending_checkout gains an optional p_tickets payload plus tickets_bought.
-- Both bodies live in the database; see v10 notes in the repo history.
