-- Product thumbnails for the interest tracker.
--
-- image_url holds a full URL (or a site-relative path such as /products/x.png),
-- so a product can point at any image source. NULL renders a placeholder.
--
-- Seeded with TCGplayer CDN thumbnails (200px wide, ~5-30 KB) matched to each
-- product by set + name. Matching is by name rather than id because product ids
-- differ between environments.

alter table public.products
  add column if not exists image_url text;

update public.products p
   set image_url = v.image_url
  from public.sets s,
       (values
  ('151', 'Binder Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/502004_200w.jpg'),
  ('151', 'Booster Bundle', 'https://tcgplayer-cdn.tcgplayer.com/product/502000_200w.jpg'),
  ('151', 'Elite Trainer Box', 'https://tcgplayer-cdn.tcgplayer.com/product/503313_200w.jpg'),
  ('151', 'Mini Tins', 'https://tcgplayer-cdn.tcgplayer.com/product/522699_200w.jpg'),
  ('151', 'Poster Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/502001_200w.jpg'),
  ('151', 'Ultra-Premium Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/502005_200w.jpg'),
  ('30th Celebration', '2 Pack Blister', 'https://tcgplayer-cdn.tcgplayer.com/product/704148_200w.jpg'),
  ('30th Celebration', 'Binder Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/704169_200w.jpg'),
  ('30th Celebration', 'Booster Bundle', 'https://tcgplayer-cdn.tcgplayer.com/product/704171_200w.jpg'),
  ('30th Celebration', 'Ditto Premium Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/704189_200w.jpg'),
  ('30th Celebration', 'Elite Trainer Box', 'https://tcgplayer-cdn.tcgplayer.com/product/704143_200w.jpg'),
  ('30th Celebration', 'ex Box Greninja', 'https://tcgplayer-cdn.tcgplayer.com/product/704168_200w.jpg'),
  ('30th Celebration', 'ex Box Sylveon', 'https://tcgplayer-cdn.tcgplayer.com/product/704155_200w.jpg'),
  ('30th Celebration', 'KO collection', 'https://tcgplayer-cdn.tcgplayer.com/product/704152_200w.jpg'),
  ('30th Celebration', 'Mew Figure Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/704193_200w.jpg'),
  ('30th Celebration', 'Mewtwo Figure Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/704194_200w.jpg'),
  ('30th Celebration', 'Mini tin', 'https://tcgplayer-cdn.tcgplayer.com/product/704177_200w.jpg'),
  ('30th Celebration', 'Mini tin display', 'https://tcgplayer-cdn.tcgplayer.com/product/704186_200w.jpg'),
  ('30th Celebration', 'Poster Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/704153_200w.jpg'),
  ('30th Celebration', 'Tech Sticker collection (Exeggutor)', 'https://tcgplayer-cdn.tcgplayer.com/product/704145_200w.jpg'),
  ('30th Celebration', 'Tech Sticker collection (Lucario)', 'https://tcgplayer-cdn.tcgplayer.com/product/704146_200w.jpg'),
  ('30th Celebration', 'UPC (Espeon)', 'https://tcgplayer-cdn.tcgplayer.com/product/704190_200w.jpg'),
  ('30th Celebration', 'UPC (Umbreon)', 'https://tcgplayer-cdn.tcgplayer.com/product/704191_200w.jpg'),
  ('Ascended Heroes', '2-Pack Blisters (Erika)', 'https://tcgplayer-cdn.tcgplayer.com/product/666906_200w.jpg'),
  ('Ascended Heroes', '2-Pack Blisters (Larry)', 'https://tcgplayer-cdn.tcgplayer.com/product/666907_200w.jpg'),
  ('Ascended Heroes', 'Ascended EX Tins (M Emboar)', 'https://tcgplayer-cdn.tcgplayer.com/product/702496_200w.jpg'),
  ('Ascended Heroes', 'Ascended EX Tins (M Feraligator)', 'https://tcgplayer-cdn.tcgplayer.com/product/702497_200w.jpg'),
  ('Ascended Heroes', 'Ascended EX Tins (M Meganium)', 'https://tcgplayer-cdn.tcgplayer.com/product/702498_200w.jpg'),
  ('Ascended Heroes', 'Ascended Mini Tins', 'https://tcgplayer-cdn.tcgplayer.com/product/668531_200w.jpg'),
  ('Ascended Heroes', 'Bundle', 'https://tcgplayer-cdn.tcgplayer.com/product/668541_200w.jpg'),
  ('Ascended Heroes', 'Deluxe Pin Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/672391_200w.jpg'),
  ('Ascended Heroes', 'Elite Trainer Box', 'https://tcgplayer-cdn.tcgplayer.com/product/668496_200w.jpg'),
  ('Ascended Heroes', 'Gardevoir Poster Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/668537_200w.jpg'),
  ('Ascended Heroes', 'Lucario Poster Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/668536_200w.jpg'),
  ('Ascended Heroes', 'Tech Sticker Collection (Charmander)', 'https://tcgplayer-cdn.tcgplayer.com/product/666908_200w.jpg'),
  ('Ascended Heroes', 'Tech Sticker Collection (Gastly)', 'https://tcgplayer-cdn.tcgplayer.com/product/666909_200w.jpg'),
  ('Black Bolt / White Flare', 'Black Bolt Binder Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/630430_200w.jpg'),
  ('Black Bolt / White Flare', 'Black Bolt Booster Bundle', 'https://tcgplayer-cdn.tcgplayer.com/product/630431_200w.jpg'),
  ('Black Bolt / White Flare', 'Black Bolt Elite Trainer Box', 'https://tcgplayer-cdn.tcgplayer.com/product/630686_200w.jpg'),
  ('Black Bolt / White Flare', 'White Flare Binder Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/630695_200w.jpg'),
  ('Black Bolt / White Flare', 'White Flare Booster Bundle', 'https://tcgplayer-cdn.tcgplayer.com/product/630696_200w.jpg'),
  ('Black Bolt / White Flare', 'White Flare Elite Trainer Box', 'https://tcgplayer-cdn.tcgplayer.com/product/630689_200w.jpg'),
  ('Chaos Rising', 'Booster Box', 'https://tcgplayer-cdn.tcgplayer.com/product/684444_200w.jpg'),
  ('Chaos Rising', 'Bundle', 'https://tcgplayer-cdn.tcgplayer.com/product/684456_200w.jpg'),
  ('Chaos Rising', 'Elite Trainer Box', 'https://tcgplayer-cdn.tcgplayer.com/product/684450_200w.jpg'),
  ('Chaos Rising', 'Single Packs', 'https://tcgplayer-cdn.tcgplayer.com/product/684446_200w.jpg'),
  ('Destined Rivals', 'Booster Box', 'https://tcgplayer-cdn.tcgplayer.com/product/624679_200w.jpg'),
  ('Destined Rivals', 'Bundle', 'https://tcgplayer-cdn.tcgplayer.com/product/625670_200w.jpg'),
  ('Destined Rivals', 'Elite Trainer Box', 'https://tcgplayer-cdn.tcgplayer.com/product/624676_200w.jpg'),
  ('Destined Rivals', 'Single Packs', 'https://tcgplayer-cdn.tcgplayer.com/product/624683_200w.jpg'),
  ('Destined Rivals', 'Sleeved Case', 'https://tcgplayer-cdn.tcgplayer.com/product/628413_200w.jpg'),
  ('Journey Together', 'Booster Box', 'https://tcgplayer-cdn.tcgplayer.com/product/610931_200w.jpg'),
  ('Journey Together', 'Bundle', 'https://tcgplayer-cdn.tcgplayer.com/product/610953_200w.jpg'),
  ('Journey Together', 'Elite Trainer Box', 'https://tcgplayer-cdn.tcgplayer.com/product/610930_200w.jpg'),
  ('Journey Together', 'Single Packs', 'https://tcgplayer-cdn.tcgplayer.com/product/610935_200w.jpg'),
  ('Mega Evolution', 'Booster Box', 'https://tcgplayer-cdn.tcgplayer.com/product/644298_200w.jpg'),
  ('Mega Evolution', 'Bundle', 'https://tcgplayer-cdn.tcgplayer.com/product/644362_200w.jpg'),
  ('Mega Evolution', 'Elite Trainer Box', 'https://tcgplayer-cdn.tcgplayer.com/product/644279_200w.jpg'),
  ('Mega Evolution', 'Single Packs', 'https://tcgplayer-cdn.tcgplayer.com/product/644352_200w.jpg'),
  ('Perfect Order', 'Booster Box', 'https://tcgplayer-cdn.tcgplayer.com/product/672394_200w.jpg'),
  ('Perfect Order', 'Bundle', 'https://tcgplayer-cdn.tcgplayer.com/product/672396_200w.jpg'),
  ('Perfect Order', 'Elite Trainer Box', 'https://tcgplayer-cdn.tcgplayer.com/product/672401_200w.jpg'),
  ('Perfect Order', 'Single Packs', 'https://tcgplayer-cdn.tcgplayer.com/product/672398_200w.jpg'),
  ('Phantasmal Flames', 'Booster Box', 'https://tcgplayer-cdn.tcgplayer.com/product/654137_200w.jpg'),
  ('Phantasmal Flames', 'Bundle', 'https://tcgplayer-cdn.tcgplayer.com/product/654160_200w.jpg'),
  ('Phantasmal Flames', 'Elite Trainer Box', 'https://tcgplayer-cdn.tcgplayer.com/product/654136_200w.jpg'),
  ('Phantasmal Flames', 'Single Packs', 'https://tcgplayer-cdn.tcgplayer.com/product/654144_200w.jpg'),
  ('Pitch Black', 'Booster Box', 'https://tcgplayer-cdn.tcgplayer.com/product/692939_200w.jpg'),
  ('Pitch Black', 'Bundle', 'https://tcgplayer-cdn.tcgplayer.com/product/692942_200w.jpg'),
  ('Pitch Black', 'Elite Trainer Box', 'https://tcgplayer-cdn.tcgplayer.com/product/692947_200w.jpg'),
  ('Pitch Black', 'Single Packs', 'https://tcgplayer-cdn.tcgplayer.com/product/692944_200w.jpg'),
  ('Prismatic Evolutions', 'Accessory Pouch Special Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/606881_200w.jpg'),
  ('Prismatic Evolutions', 'Binder Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/593356_200w.jpg'),
  ('Prismatic Evolutions', 'Booster Bundle', 'https://tcgplayer-cdn.tcgplayer.com/product/600518_200w.jpg'),
  ('Prismatic Evolutions', 'Elite Trainer Box', 'https://tcgplayer-cdn.tcgplayer.com/product/593355_200w.jpg'),
  ('Prismatic Evolutions', 'Mini Tins', 'https://tcgplayer-cdn.tcgplayer.com/product/593459_200w.jpg'),
  ('Prismatic Evolutions', 'Pokemon Center Elite Trainer Box', 'https://tcgplayer-cdn.tcgplayer.com/product/593324_200w.jpg'),
  ('Prismatic Evolutions', 'Poster Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/593359_200w.jpg'),
  ('Prismatic Evolutions', 'Premium Figure Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/650799_200w.jpg'),
  ('Prismatic Evolutions', 'Super-Premium Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/622770_200w.jpg'),
  ('Prismatic Evolutions', 'Surprise Box', 'https://tcgplayer-cdn.tcgplayer.com/product/593466_200w.jpg'),
  ('Prismatic Evolutions', 'Tech Sticker Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/593450_200w.jpg'),
  ('Special Collections', '2026 Pokemon Day 3-Pack', 'https://tcgplayer-cdn.tcgplayer.com/product/668590_200w.jpg'),
  ('Special Collections', 'BB/WF Heavy Hitters Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/668632_200w.jpg'),
  ('Special Collections', 'Charizard EX Premium Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/516576_200w.jpg'),
  ('Special Collections', 'Charizard EX UPC', 'https://tcgplayer-cdn.tcgplayer.com/product/654213_200w.jpg'),
  ('Special Collections', 'First Partner Collection S2', 'https://tcgplayer-cdn.tcgplayer.com/product/688712_200w.jpg'),
  ('Special Collections', 'First Partner Illustration Collection S1', 'https://tcgplayer-cdn.tcgplayer.com/product/673436_200w.jpg'),
  ('Special Collections', 'First Partner Series 3', 'https://tcgplayer-cdn.tcgplayer.com/product/695400_200w.jpg'),
  ('Special Collections', 'Gengar Battle Deck', 'https://tcgplayer-cdn.tcgplayer.com/product/659192_200w.jpg'),
  ('Special Collections', 'Great Tusk Collection Box', 'https://tcgplayer-cdn.tcgplayer.com/product/665113_200w.jpg'),
  ('Special Collections', 'Lucario Figure Box', 'https://tcgplayer-cdn.tcgplayer.com/product/656487_200w.jpg'),
  ('Special Collections', 'Moltres UPC', 'https://tcgplayer-cdn.tcgplayer.com/product/656997_200w.jpg'),
  ('Special Collections', 'Prismatic Figure Collection', 'https://tcgplayer-cdn.tcgplayer.com/product/650799_200w.jpg'),
  ('Special Collections', 'Prismatic SPC', 'https://tcgplayer-cdn.tcgplayer.com/product/622770_200w.jpg'),
  ('Surging Sparks', 'Booster Box', 'https://tcgplayer-cdn.tcgplayer.com/product/565606_200w.jpg'),
  ('Surging Sparks', 'Bundle', 'https://tcgplayer-cdn.tcgplayer.com/product/679564_200w.jpg'),
  ('Surging Sparks', 'Elite Trainer Box', 'https://tcgplayer-cdn.tcgplayer.com/product/565630_200w.jpg'),
  ('Surging Sparks', 'Single Packs', 'https://tcgplayer-cdn.tcgplayer.com/product/565604_200w.jpg'),
  ('Tins', 'Charizard X Tin', 'https://tcgplayer-cdn.tcgplayer.com/product/671250_200w.jpg'),
  ('Tins', 'Charizard Y Tin', 'https://tcgplayer-cdn.tcgplayer.com/product/671249_200w.jpg'),
  ('Tins', 'Lumiose City Mini Tin (PO+CRI)', 'https://tcgplayer-cdn.tcgplayer.com/product/685575_200w.jpg'),
  ('Tins', 'Mega Forces Tin (M Darkrai)', 'https://tcgplayer-cdn.tcgplayer.com/product/702506_200w.jpg'),
  ('Tins', 'Mega Forces Tin (M Dragonite)', 'https://tcgplayer-cdn.tcgplayer.com/product/702505_200w.jpg'),
  ('Tins', 'Mega Forces Tin (M Zeraora)', 'https://tcgplayer-cdn.tcgplayer.com/product/702507_200w.jpg'),
  ('Tins', 'Mega Moonlit Tin (Clefable)', 'https://tcgplayer-cdn.tcgplayer.com/product/686438_200w.jpg'),
  ('Tins', 'Mega Moonlit Tin (Gengar)', 'https://tcgplayer-cdn.tcgplayer.com/product/686437_200w.jpg')
       ) as v(set_name, product_name, image_url)
 where p.set_id = s.id
   and s.name = v.set_name
   and p.name = v.product_name
   and p.image_url is null;
